/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaDeNegocio.ProductosBL;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author alulab14
 */
public class frmAvisoStock extends javax.swing.JDialog {

    /**
     * Creates new form frmAvisoStock
     */
    public frmAvisoStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Producto producto=new Producto();
        
        initComponents();
        jCod.setSelected(true);
        ArrayList<Producto>productos=new ArrayList<Producto>();
        ProductosBL productoBL=new ProductosBL();
        
        DefaultTableModel model=(DefaultTableModel) tblProd.getModel();
        try{
            productos=productoBL.listarProductos();
            
            Object rowData[]=new Object[4];
            for(int i=0;i<productos.size();i++){
                if(productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                rowData[0]=productos.get(i).getCodigo();
                rowData[1]=productos.get(i).getNombre();

                rowData[2]=productos.get(i).getStock();
                rowData[3]=productos.get(i).getMinimoStock();
                model.addRow(rowData);
                }
            }
        }catch (Exception e){
           System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        jCod = new javax.swing.JRadioButton();
        jNomb = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(634, 522));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/015-search.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));

        tblProd=new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblProd.setBackground(new java.awt.Color(255, 255, 204));
        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Stock", "Stock Minimo"
            }
        ));
        tblProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblProd.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblProd.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblProd.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jCod.setBackground(new java.awt.Color(204, 204, 204));
        jCod.setText("Codigo");
        jCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodActionPerformed(evt);
            }
        });

        jNomb.setBackground(new java.awt.Color(204, 204, 204));
        jNomb.setText("Nombre");
        jNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/002-checked.png"))); // NOI18N
        btnCancelar.setText("OK");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BAJOS DE STOCK:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LOS SIGUIENTES PRODUCTOS SE ENCUENTRAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNomb))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCod)
                    .addComponent(jNomb)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombActionPerformed
        // TODO add your handling code here:
        if(jCod.isSelected()==true){
            jNomb.setSelected(true);
            jCod.setSelected(false);
        }
    }//GEN-LAST:event_jNombActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodActionPerformed
        // TODO add your handling code here:
        if(jNomb.isSelected()==true){
            jCod.setSelected(true);
            jNomb.setSelected(false);
        }
    }//GEN-LAST:event_jCodActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            ArrayList<Producto>listaBusq=new ArrayList<Producto>();
            ArrayList<Producto>productos=new ArrayList<Producto>();
            ProductosBL productoBL=new ProductosBL();
            productos=productoBL.listarProductos();
            DefaultTableModel model=(DefaultTableModel) tblProd.getModel();

            String criterio;
            criterio=jTextField1.getText().toString().trim();
            if(jTextField1.getText().isEmpty()){
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                    rowData[0]=productos.get(i).getCodigo();
                    rowData[1]=productos.get(i).getNombre();

                    rowData[2]=productos.get(i).getStock();
                    rowData[3]=productos.get(i).getMinimoStock();
                    model.addRow(rowData);
                    }
                }
            }
            if(jCod.isSelected()){
                criterio=criterio.toUpperCase();
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getCodigo().contains(criterio)&&productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    
                    rowData[2]=listaBusq.get(i).getStock();
                    rowData[3]=listaBusq.get(i).getMinimoStock();
                    model.addRow(rowData);
                }
            }
            if(jNomb.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getNombre().contains(criterio)&&productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    
                    rowData[2]=listaBusq.get(i).getStock();
                    rowData[3]=listaBusq.get(i).getMinimoStock();
                    model.addRow(rowData);
                }
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try{
            ArrayList<Producto>listaBusq=new ArrayList<Producto>();
            ArrayList<Producto>productos=new ArrayList<Producto>();
            ProductosBL productoBL=new ProductosBL();
            productos=productoBL.listarProductos();
            DefaultTableModel model=(DefaultTableModel) tblProd.getModel();

            String criterio;
            criterio=jTextField1.getText().toString().trim();
            if(jTextField1.getText().isEmpty()){
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                    rowData[0]=productos.get(i).getCodigo();
                    rowData[1]=productos.get(i).getNombre();

                    rowData[2]=productos.get(i).getStock();
                    rowData[3]=productos.get(i).getMinimoStock();
                    model.addRow(rowData);
                    }
                }
            }
            if(jCod.isSelected()){
                criterio=criterio.toUpperCase();
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getCodigo().contains(criterio)&&productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    
                    rowData[2]=listaBusq.get(i).getStock();
                    rowData[3]=listaBusq.get(i).getMinimoStock();
                    model.addRow(rowData);
                }
            }
            if(jNomb.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getNombre().contains(criterio)&&productos.get(i).getStock()<=productos.get(i).getMinimoStock()){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[4];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    
                    rowData[2]=listaBusq.get(i).getStock();
                    rowData[3]=listaBusq.get(i).getMinimoStock();
                    model.addRow(rowData);
                }
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAvisoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAvisoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAvisoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAvisoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAvisoStock dialog = new frmAvisoStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton4;
    private javax.swing.JRadioButton jCod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jNomb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblProd;
    // End of variables declaration//GEN-END:variables
}
