/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaDeNegocio.AlmacenesBL;
import static Vista.frmPanel.contador;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelo.Almacen;

/**
 *
 * @author alulab14
 */
public class frmGestAlma extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmGestAlma
     */
    public Almacen almacenG;
    public Almacen getAlmacen() {
        return almacenG;
    }

    public void setAlmacen(Almacen almacen) {
        this.almacenG = almacen;
    }
    public frmGestAlma() {
        almacenG=new Almacen();
        ArrayList<Almacen> almacenes=new ArrayList<Almacen>();
        BasicInternalFrameUI basic=((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener:basic.getNorthPane().getMouseListeners()){
            basic.getNorthPane().removeMouseListener(listener);
        }
        initComponents();
        
        AlmacenesBL almacenBL=new AlmacenesBL();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        try{
            almacenes=almacenBL.listarAlmacenes();
            Object rowData[]=new Object[8];
            for(int i=0;i<almacenes.size();i++){
                rowData[0]=almacenes.get(i).getIdalmacen();
                rowData[1]=almacenes.get(i).getDireccion();
                rowData[2]=almacenes.get(i).getNumDifProd();
                model.addRow(rowData);
            }
        }catch (Exception e){
            System.out.println("Error de bd");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(650, 680));
        setPreferredSize(new java.awt.Dimension(650, 680));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/003-plus.png"))); // NOI18N
        jButton1.setText("Añadir");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/008-settings.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1=new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Almacen", "Dirección", "Num. distintos prod"
            }
        ));
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/004-error.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/004-error.png"))); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmAddAlmacen addA=new frmAddAlmacen(null,true);
        addA.setVisible(true);
        if(addA.isVisible()==false){
//            JOptionPane.showConfirmDialog(this,"cerro","Aviso",WARNING_MESSAGE);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            AlmacenesBL almacenBL=new AlmacenesBL();
            ArrayList<Almacen>almacenes=new ArrayList<Almacen>();
            try{
            almacenes=almacenBL.listarAlmacenes();
            Object rowData[]=new Object[8];
            for(int i=0;i<almacenes.size();i++){
                rowData[0]=almacenes.get(i).getIdalmacen();
                rowData[1]=almacenes.get(i).getDireccion();
                rowData[2]=almacenes.get(i).getNumDifProd();
                model.addRow(rowData);
            }
        }catch (Exception e){
            System.out.println("Error de bd");
        }
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row;
        if(jTable1.getSelectedRow()!=-1){
        row = jTable1.getSelectedRow();
        
        int id=Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        int numDif=Integer.parseInt(jTable1.getModel().getValueAt(row,2).toString());
        String dir=jTable1.getModel().getValueAt(row,1).toString();
        
        almacenG.setDireccion(dir);
        almacenG.setEstado(1);
        almacenG.setIdalmacen(id);
        almacenG.setNumDifProd(numDif);
        
        frmModifAlmacen mod=new frmModifAlmacen(null,true,almacenG);
        mod.setVisible(true);
        if(mod.isVisible()==false){
//            JOptionPane.showConfirmDialog(this,"cerro","Aviso",WARNING_MESSAGE);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            AlmacenesBL almacenBL=new AlmacenesBL();
            ArrayList<Almacen>almacenes=new ArrayList<Almacen>();
            try{
            almacenes=almacenBL.listarAlmacenes();
            Object rowData[]=new Object[8];
            for(int i=0;i<almacenes.size();i++){
                rowData[0]=almacenes.get(i).getIdalmacen();
                rowData[1]=almacenes.get(i).getDireccion();
                rowData[2]=almacenes.get(i).getNumDifProd();
                model.addRow(rowData);
            }
        }catch (Exception e){
            System.out.println("Error de bd");
        }
            
        }
        }else JOptionPane.showMessageDialog(this,"Seleccione el almacen","Advertencia",WARNING_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
        int resultado=JOptionPane.showConfirmDialog(null,"¿Seguro que desea eliminar el almacen?");
        if(resultado==JOptionPane.YES_OPTION){
            int column=0;
            int row=jTable1.getSelectedRow();
            int id=Integer.parseInt(jTable1.getModel().getValueAt(row, column).toString());
            AlmacenesBL almacenBL=new AlmacenesBL();
            try{
                almacenBL.eliminarAlmacen(id);
            }catch(Exception ex){
                System.out.println(ex);
            }
            
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            ArrayList<Almacen>almacenes=new ArrayList<Almacen>();
            try{
            almacenes=almacenBL.listarAlmacenes();
            Object rowData[]=new Object[8];
            for(int i=0;i<almacenes.size();i++){
                rowData[0]=almacenes.get(i).getIdalmacen();
                rowData[1]=almacenes.get(i).getDireccion();
                rowData[2]=almacenes.get(i).getNumDifProd();
                model.addRow(rowData);
            }
        }catch (Exception e){
            System.out.println("Error de bd");
        }
        }
        }else JOptionPane.showMessageDialog(this,"Seleccione el almacen","Advertencia",WARNING_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        contador--;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
