/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaDeNegocio.ProductosBL;
import LogicaDeNegocio.ProveedoresBL;
import static Vista.frmPanel.i;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Proveedor;

/**
 *
 * @author Usuario
 */
public class frmGestProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmGestProveedores
     */
    public Proveedor proveedor;
    public frmGestProveedores() {
        proveedor=new Proveedor();
        ArrayList<Proveedor> proveedores=new ArrayList<Proveedor>();
        initComponents();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        ProveedoresBL proveedorBL=new ProveedoresBL();
        try{
            proveedores=proveedorBL.listarProveedores();
            Object rowData[]=new Object[8];
            for(int i=0;i<proveedores.size();i++){
                rowData[0]=proveedores.get(i).getRazonSoc();
                rowData[1]=proveedores.get(i).getRuc();
                rowData[2]=proveedores.get(i).getEmail();
                rowData[3]=proveedores.get(i).getTelefono();
                rowData[4]=proveedores.get(i).getDireccion();
                model.addRow(rowData);
            }
        }catch (Exception e){
            System.out.println("Error de bd");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBusqueda = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));

        jPanel1.setBackground(new java.awt.Color(0, 122, 204));
        jPanel1.setToolTipText("");

        jButton2.setBackground(new java.awt.Color(0, 122, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/008-settings.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 122, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/004-error.png"))); // NOI18N
        jButton3.setText(" Eliminar");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 122, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/015-search.png"))); // NOI18N
        jButton4.setText(" Buscar");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razon Social", "RUC", "E-mail", "Teléfono", "Direccion"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 122, 204));
        jScrollPane1.setViewportView(jTable1);

        lblBusqueda.setText("...");
        lblBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusquedaMouseClicked(evt);
            }
        });
        lblBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBusquedaActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(0, 122, 204));
        jRadioButton1.setText("RUC");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 122, 204));
        jRadioButton2.setText("Nombre");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 122, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/003-plus.png"))); // NOI18N
        jButton1.setText(" Agregar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 122, 204));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/004-error.png"))); // NOI18N
        btnCancel.setText("Regresar");
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))
                            .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int row;
        if(jTable1.getSelectedRow()!=-1){
            row = jTable1.getSelectedRow();
            String razon=jTable1.getModel().getValueAt(row,0).toString();
            String ruc=jTable1.getModel().getValueAt(row,1).toString();
            String email=jTable1.getModel().getValueAt(row,2).toString();
            int telefono=Integer.parseInt(jTable1.getModel().getValueAt(row,3).toString());
            String dir=jTable1.getModel().getValueAt(row,4).toString();

            proveedor.setRazonSoc(razon);
            proveedor.setEmail(email);
            proveedor.setTelefono(telefono);
            proveedor.setDireccion(dir);
            
        frmModifProveedor modP= new frmModifProveedor(null,true,proveedor,ruc);
        modP.setVisible(true);
        
        if(modP.isVisible()==false){
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            ProveedoresBL proveedorBL=new ProveedoresBL();
            try{
                model.setRowCount(0);
                ArrayList<Proveedor> proveedores=new ArrayList<Proveedor>();
                proveedores=proveedorBL.listarProveedores();
                Object rowData[]=new Object[8];
                for(int i=0;i<proveedores.size();i++){
                    rowData[0]=proveedores.get(i).getRazonSoc();
                    rowData[1]=proveedores.get(i).getRuc();
                    rowData[2]=proveedores.get(i).getEmail();
                    rowData[3]=proveedores.get(i).getTelefono();
                    rowData[4]=proveedores.get(i).getDireccion();
                    model.addRow(rowData);
                }
            }catch (Exception e){
                System.out.println("Error de bd");
            }
        }
        }else JOptionPane.showMessageDialog(this,"Seleccione el proveedor","Advertencia",WARNING_MESSAGE);   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
        int result=JOptionPane.showConfirmDialog(null,"¿Seguro que desea eliminar el proveedor?");
        if(result==JOptionPane.YES_OPTION){
            int column=1;
            int row=jTable1.getSelectedRow();
            String ruc=jTable1.getModel().getValueAt(row, column).toString();
            
            ProveedoresBL provBL=new ProveedoresBL();
            try{
                provBL.eliminarProveedor(ruc);
            }catch(Exception ex){
                System.out.println(ex);
            }
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            ArrayList<Proveedor>proveedores=new ArrayList<Proveedor>();
            try{
            proveedores=provBL.listarProveedores();
            Object rowData[]=new Object[8];
            for(int i=0;i<proveedores.size();i++){
                rowData[0]=proveedores.get(i).getRazonSoc();
                rowData[1]=proveedores.get(i).getRuc();
                rowData[2]=proveedores.get(i).getEmail();
                rowData[3]=proveedores.get(i).getTelefono();
                rowData[4]=proveedores.get(i).getDireccion();
                model.addRow(rowData);
            }
        }catch (Exception e){
           System.out.println("Error de bd");
        }
        }
        }else JOptionPane.showMessageDialog(this,"Seleccione el proveedor","Advertencia",WARNING_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lblBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusquedaMouseClicked
        // TODO add your handling code here:
        if(i==0)
        lblBusqueda.setText("");
        i++;
    }//GEN-LAST:event_lblBusquedaMouseClicked

    private void lblBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBusquedaActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()==true){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()==true){
            jRadioButton2.setSelected(true);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmAddProveedor addP= new frmAddProveedor(null, true);
        addP.setVisible(true);
        if (addP.isVisible()==false){
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            ProveedoresBL proveedorBL=new ProveedoresBL();
            try{
                model.setRowCount(0);
                ArrayList<Proveedor> proveedores=new ArrayList<Proveedor>();
                proveedores=proveedorBL.listarProveedores();
                Object rowData[]=new Object[8];
                for(int i=0;i<proveedores.size();i++){
                    rowData[0]=proveedores.get(i).getRazonSoc();
                    rowData[1]=proveedores.get(i).getRuc();
                    rowData[2]=proveedores.get(i).getEmail();
                    rowData[3]=proveedores.get(i).getTelefono();
                    rowData[4]=proveedores.get(i).getDireccion();
                    model.addRow(rowData);
                }
            }catch (Exception e){
                System.out.println("Error de bd");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblBusqueda;
    // End of variables declaration//GEN-END:variables
}
