/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaDeNegocio.AlmacenesBL;
import LogicaDeNegocio.ProductosBL;
import static Vista.frmPanel.contador;
import com.sun.webkit.event.WCKeyEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelo.Almacen;
import modelo.Producto;

/**
 *
 * @author Usuario
 */
public class frmMovAlmacen extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMovAlmacen
     */
    public frmMovAlmacen() {
        ArrayList<Producto> productos=new ArrayList<Producto>();
        BasicInternalFrameUI basic=((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener:basic.getNorthPane().getMouseListeners()){
            basic.getNorthPane().removeMouseListener(listener);
        }
        initComponents();
        aumento.setSelected(true);
        jCod.setSelected(true);
        AlmacenesBL almacenBL=new AlmacenesBL();
        ProductosBL productoBL=new ProductosBL();
        DefaultTableModel model=(DefaultTableModel) jTable3.getModel();
        try{
            productos=productoBL.listarProductos();
            Object rowData[]=new Object[8];
            for(int i=0;i<productos.size();i++){
                rowData[0]=productos.get(i).getCodigo();
                rowData[1]=productos.get(i).getNombre();
                rowData[2]=productos.get(i).getStock();
                model.addRow(rowData);
            }
            
        }catch (Exception e){
            System.out.println("Error de bd");
        }
        
        ArrayList<Almacen> almacenes=new ArrayList<Almacen>();        
        try{
            almacenes=almacenBL.listarAlmacenes();
            for(Almacen almacen:almacenes){
                jComboBox1.addItem(almacen.getDireccion());
            }
            jComboBox1.setSelectedIndex(0);
        }catch (Exception e){
            System.out.println("Error de bd");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCod = new javax.swing.JRadioButton();
        jNomb = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        aumento = new javax.swing.JRadioButton();
        decremento = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(650, 680));
        setPreferredSize(new java.awt.Dimension(650, 680));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Elija el almacén al que se ingresara el producto seleccionado:");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCod.setBackground(new java.awt.Color(204, 204, 204));
        jCod.setText("Codigo");
        jCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodActionPerformed(evt);
            }
        });

        jNomb.setBackground(new java.awt.Color(204, 204, 204));
        jNomb.setText("Nombre");
        jNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/015-search.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("...");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTable3=new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable3.setBackground(new java.awt.Color(255, 255, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Stock General"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/004-error.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/png3/003-plus.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        aumento.setBackground(new java.awt.Color(204, 204, 204));
        aumento.setText("Aumento de Stock");
        aumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentoActionPerformed(evt);
            }
        });

        decremento.setBackground(new java.awt.Color(204, 204, 204));
        decremento.setText("Decremento de Stock");
        decremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elija un producto para");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("modificar su stock:");

        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aumento)
                        .addGap(18, 18, 18)
                        .addComponent(decremento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCod)
                                .addGap(10, 10, 10)
                                .addComponent(jNomb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCod)
                            .addComponent(jNomb))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aumento)
                    .addComponent(decremento)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementoActionPerformed
        // TODO add your handling code here:
        if(aumento.isSelected()){
            aumento.setSelected(false);
            decremento.setSelected(true);
        }else decremento.setSelected(true);
    }//GEN-LAST:event_decrementoActionPerformed

    private void aumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentoActionPerformed
        // TODO add your handling code here:
        if(decremento.isSelected()){
            aumento.setSelected(true);
            decremento.setSelected(false);
        }
        else aumento.setSelected(true);
    }//GEN-LAST:event_aumentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row;
        DefaultTableModel model=(DefaultTableModel) jTable3.getModel();
        if(jTable3.getSelectedRow()!=-1){
            int valor=Integer.parseInt(jSpinner1.getText());
            if(valor!=0){
                if(valor>0 && valor<9999){
                    row = jTable3.getSelectedRow();
                    String cod=jTable3.getModel().getValueAt(row,0).toString();
                    Integer stock=(Integer)jTable3.getModel().getValueAt(row,2);
                    int stockNuevo=Integer.parseInt(jSpinner1.getText());
                    ProductosBL prodBL=new ProductosBL();
                    if(decremento.isSelected())stockNuevo=stockNuevo*-1;
                    stockNuevo=stock+stockNuevo;
                    if(stockNuevo>=0){
                    try{
                        
                        prodBL.incrementarStock(stockNuevo, cod);
                        JOptionPane.showMessageDialog(this,
                            "Se modificó el stock","Aviso",
                            INFORMATION_MESSAGE);
                    }catch (Exception ex){}
                    try{
                        model.setRowCount(0);
                        ArrayList<Producto>productos=new ArrayList<Producto>();
                        productos=prodBL.listarProductos();
                        Object rowData[]=new Object[8];
                        for(int i=0;i<productos.size();i++){
                            rowData[0]=productos.get(i).getCodigo();
                            rowData[1]=productos.get(i).getNombre();
                            rowData[2]=productos.get(i).getStock();
                            model.addRow(rowData);
                        }
                    }catch (Exception e){
                        System.out.println("Error de bd");
                    }
                    }else JOptionPane.showMessageDialog(this,"El stock no puede ser negativo","Error",ERROR_MESSAGE);
                }else{ JOptionPane.showMessageDialog(this,"Ingrese un numero positivo menor a 9999","Advertencia",WARNING_MESSAGE);
                    jSpinner1.setText("0");
                }
            }
            else JOptionPane.showMessageDialog(this,"Ingrese una cantidad mayor a 0","Advertencia",WARNING_MESSAGE);
        }else JOptionPane.showMessageDialog(this,"Seleccione el producto","Advertencia",WARNING_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        contador--;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            ArrayList<Producto>listaBusq=new ArrayList<Producto>();
            ArrayList<Producto>productos=new ArrayList<Producto>();
            ProductosBL productoBL=new ProductosBL();
            productos=productoBL.listarProductos();
            DefaultTableModel model=(DefaultTableModel) jTable3.getModel();

            String criterio;
            criterio=jTextField1.getText().toString().trim();
            if(jTextField1.getText().isEmpty()){
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=productos.get(i).getCodigo();
                    rowData[1]=productos.get(i).getNombre();
                    rowData[2]=productos.get(i).getStock();
                    model.addRow(rowData);
                }
            }
            if(jCod.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getCodigo().contains(criterio)){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<listaBusq.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    rowData[2]=listaBusq.get(i).getStock();
                    model.addRow(rowData);
                }
            }
            if(jNomb.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getNombre().contains(criterio)){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<listaBusq.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    rowData[2]=listaBusq.get(i).getStock();
                    model.addRow(rowData);
                }
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jNombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombActionPerformed
        // TODO add your handling code here:
        if(jCod.isSelected()==true){
            jNomb.setSelected(true);
            jCod.setSelected(false);
        }
    }//GEN-LAST:event_jNombActionPerformed

    private void jCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodActionPerformed
        // TODO add your handling code here:
        if(jNomb.isSelected()==true){
            jCod.setSelected(true);
            jNomb.setSelected(false);
        }
    }//GEN-LAST:event_jCodActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSpinner1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyTyped
        // TODO add your handling code here:
        String s1=String.valueOf(evt.getKeyChar());
        if(evt.getKeyChar()!=WCKeyEvent.VK_BACK){
            if(jSpinner1.getText().length()>=5){
                evt.consume();
            
            }
            if(!s1.matches("[0-9]")){
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(this,
                "Solo se admiten numeros","Error",
                ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jSpinner1KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try{
            ArrayList<Producto>listaBusq=new ArrayList<Producto>();
            ArrayList<Producto>productos=new ArrayList<Producto>();
            ProductosBL productoBL=new ProductosBL();
            productos=productoBL.listarProductos();
            DefaultTableModel model=(DefaultTableModel) jTable3.getModel();

            String criterio;
            criterio=jTextField1.getText().toString().trim();
            if(jTextField1.getText().isEmpty()){
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<productos.size();i++){
                    rowData[0]=productos.get(i).getCodigo();
                    rowData[1]=productos.get(i).getNombre();
                    rowData[2]=productos.get(i).getStock();
                    model.addRow(rowData);
                }
            }
            if(jCod.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getCodigo().contains(criterio)){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<listaBusq.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    rowData[2]=listaBusq.get(i).getStock();
                    model.addRow(rowData);
                }
            }
            if(jNomb.isSelected()){
                for(int i=0;i<productos.size();i++){
                    if(productos.get(i).getNombre().contains(criterio)){
                        Producto prod=new Producto();
                        prod=productos.get(i);
                        listaBusq.add(prod);
                    }
                }
                model.setRowCount(0);
                Object rowData[]=new Object[8];
                for(int i=0;i<listaBusq.size();i++){
                    rowData[0]=listaBusq.get(i).getCodigo();
                    rowData[1]=listaBusq.get(i).getNombre();
                    rowData[2]=listaBusq.get(i).getStock();
                    model.addRow(rowData);
                }
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aumento;
    private javax.swing.JRadioButton decremento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JRadioButton jCod;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jNomb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSpinner1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
